import { test, expect } from './fixtures'
import type { Page } from '@playwright/test'

type Frame = { title: string; x: number; y: number; w: number; h: number; color: string; members: string[] }
type Layout = { schema: number; cards: Record<string, { x: number; y: number }>; frames: Record<string, Frame> }
async function layout(page: Page): Promise<Layout> {
  const response = await page.request.get(new URL('/api/board', page.url()).href)
  return (await response.json()).layout
}
async function saved(page: Page, action: () => Promise<unknown>) {
  const response = page.waitForResponse(r => r.url().endsWith('/api/layout') && r.request().method() === 'PUT')
  await action()
  expect((await response).status()).toBe(200)
  await expect(page.locator('#framePanel').getByText('Saving.', { exact: false })).toHaveCount(0)
  await expect(page.locator('#btnFrame')).toBeEnabled()
}
async function createFrame(page: Page, title: string, x: number, y: number, w: number, h: number) {
  await page.locator('#btnFrame').click()
  const panel = page.locator('#framePanel')
  await panel.getByLabel('Frame title', { exact: true }).fill(title)
  for (const [label, value] of Object.entries({ X: x, Y: y, Width: w, Height: h })) {
    await panel.getByLabel(label, { exact: true }).fill(String(value))
  }
  await saved(page, () => panel.getByRole('button', { name: 'Create and capture', exact: true }).click())
  const data = await layout(page)
  return Object.keys(data.frames).find(id => data.frames[id].title === title)!
}

test('frame capture, grouped movement, boundary resize, delete and session undo preserve card data', async ({ app, page }) => {
  const a = await app.create('Frame member A', { x: 80, y: 100 })
  const b = await app.create('Frame member B', { x: 390, y: 100 })
  const outside = await app.create('Nonmember', { x: 1200, y: 700 })
  await page.goto(app.url)
  await expect(page.locator('.card')).toHaveCount(3)
  await page.locator('#search').fill('Frame member A')
  const before = await layout(page)
  const filesBefore = await app.snapshot()
  const id = await createFrame(page, 'Delivery', 40, 60, 720, 480)
  let data = await layout(page)
  expect(data.frames[id].members.sort()).toEqual([a.id, b.id].sort())
  expect(data.cards).toEqual(before.cards)
  const panel = page.locator('#framePanel')
  await panel.getByLabel('X', { exact: true }).fill('140')
  await saved(page, () => panel.getByRole('button', { name: 'Move frame and members', exact: true }).click())
  data = await layout(page)
  expect(data.cards[a.id].x).toBe(180)
  expect(data.cards[b.id].x).toBe(490)
  expect(data.cards[outside.id]).toEqual(before.cards[outside.id])
  await saved(page, () => page.locator('#btnFrameUndo').click())
  expect((await layout(page)).cards).toEqual(before.cards)
  await saved(page, () => page.locator('#btnFrameRedo').click())
  const moved = await layout(page)
  await panel.getByLabel('Width', { exact: true }).fill('900')
  await saved(page, () => panel.getByRole('button', { name: 'Resize boundary only', exact: true }).click())
  expect((await layout(page)).cards).toEqual(moved.cards)
  await saved(page, () => panel.getByRole('button', { name: 'Delete frame only', exact: true }).click())
  expect((await layout(page)).frames[id]).toBeUndefined()
  expect((await layout(page)).cards).toEqual(moved.cards)
  await saved(page, () => page.locator('#btnFrameUndo').click())
  expect((await layout(page)).frames[id].members.sort()).toEqual([a.id, b.id].sort())
  const filesAfter = await app.snapshot()
  for (const [path, content] of Object.entries(filesBefore)) if (!path.startsWith('canvas/')) expect(filesAfter[path]).toBe(content)
  await page.reload()
  await expect(page.locator('.canvas-frame')).toHaveCount(1)
  await expect(page.locator('#btnFrameUndo')).toBeDisabled()
})

test('membership is explicit and later member movement blocks frame undo', async ({ app, page }) => {
  const a = await app.create('Member A', { x: 80, y: 100 })
  await page.goto(app.url)
  await expect(page.locator('.card')).toHaveCount(1)
  const id = await createFrame(page, 'Delivery', 40, 60, 500, 500)
  await page.locator('#framePanel').getByLabel('X', { exact: true }).fill('140')
  await saved(page, () => page.getByRole('button', { name: 'Move frame and members', exact: true }).click())
  const response = await page.request.put(`${app.url}/api/layout`, { data: { board: 'default', cards: { [a.id]: { x: 1100, y: 900 } } } })
  expect(response.status()).toBe(200)
  await expect(page.locator('#frameHistory')).toContainText('Undo blocked')
  await expect(page.locator('#btnFrameUndo')).toBeDisabled()
  expect((await layout(page)).frames[id].members).toEqual([a.id])
  await page.locator('#framePanel').getByRole('button', { name: 'Close frame panel' }).click()
  await page.locator('#btnFit').click()
  await page.locator(`.card[data-id="${a.id}"] .card-title`).click()
  const membership = page.getByRole('region', { name: 'Frame membership', exact: true })
  await expect(membership).toContainText('Delivery')
  await saved(page, () => membership.getByRole('button', { name: 'Remove from frame', exact: true }).click())
  expect((await layout(page)).frames[id].members).toEqual([])
  expect((await layout(page)).cards[a.id]).toEqual({ x: 1100, y: 900 })
  await saved(page, () => membership.getByRole('button', { name: 'Add to frame', exact: true }).click())
  expect((await layout(page)).frames[id].members).toEqual([a.id])
})

test('pointer group movement restores automatic ownership without shifting nonmembers', async ({ app, page }) => {
  const a = await app.create('Automatic member A')
  const b = await app.create('Automatic member B')
  const c = await app.create('Automatic nonmember C')
  await page.goto(app.url)
  await expect(page.locator('.card')).toHaveCount(3)
  // The frame has to take the first two automatic rows and miss the third, so
  // size it from where the third card actually sits. A literal height encodes
  // the row pitch: 700 worked at a pitch of 340 and captured all three cards
  // when the pitch moved to 269.
  const rowOf = (card: string) => page.locator(`.card[data-id="${card}"]`).evaluate(node =>
    Number((node as HTMLElement).style.transform.match(/translate\(-?[\d.]+px,\s*(-?[\d.]+)px\)/)![1]))
  const secondRow = await rowOf(b.id)
  const thirdRow = await rowOf(c.id)
  const id = await createFrame(page, 'Automatic group', -20, -40, 400, thirdRow + 20)
  expect((await layout(page)).frames[id].members.sort()).toEqual([a.id, b.id].sort())
  const originalNonmember = await page.locator(`.card[data-id="${c.id}"]`).getAttribute('style')
  await page.locator('#btnFit').click()
  const title = page.locator(`.canvas-frame[data-frame-id="${id}"] .canvas-frame-title`)
  const box = (await title.boundingBox())!
  const k = await page.locator('#scene').evaluate(el => new DOMMatrix(getComputedStyle(el).transform).a)
  await saved(page, async () => {
    await page.mouse.move(box.x + 20, box.y + 10)
    await page.mouse.down()
    await page.mouse.move(box.x + 20 + 50 * k, box.y + 10 + 40 * k, { steps: 5 })
    await page.mouse.up()
  })
  let data = await layout(page)
  expect(data.frames[id].x).toBe(30)
  expect(data.cards[a.id]).toEqual({ x: 50, y: 40 })
  expect(data.cards[b.id]).toEqual({ x: 50, y: secondRow + 40 })
  expect(data.cards[c.id]).toBeUndefined()
  expect(await page.locator(`.card[data-id="${c.id}"]`).getAttribute('style')).toBe(originalNonmember)
  await saved(page, () => page.locator('#btnFrameUndo').click())
  data = await layout(page)
  expect(data.cards).toEqual({})
  await expect(page.locator(`.card[data-id="${a.id}"]`)).toHaveClass(/unpinned/)
  // Escape during a real gesture never submits a write.
  const start = (await title.boundingBox())!
  await page.mouse.move(start.x + 20, start.y + 10)
  await page.mouse.down()
  await page.mouse.move(start.x + 60, start.y + 30, { steps: 3 })
  await page.keyboard.press('Escape')
  await page.mouse.up()
  expect(await layout(page)).toEqual(data)
})

test('frame history survives board switches and delayed saves stay on their initiating board', async ({ app, page }) => {
  await app.create('Member', { x: 80, y: 100 })
  await page.goto(app.url)
  await expect(page.locator('.card')).toHaveCount(1)
  const id = await createFrame(page, 'Delivery', 40, 60, 500, 500)
  await page.request.put(`${app.url}/api/layout`, { data: { board: 'other', cards: {} } })
  await expect(page.locator('#boardSelect option[value="other"]')).toHaveCount(1)
  let finish!: () => void
  const hold = new Promise<void>(resolve => { finish = resolve })
  await page.route('**/api/layout', async route => {
    const response = await route.fetch()
    await hold
    await route.fulfill({ response })
  })
  await page.locator('#framePanel').getByLabel('X', { exact: true }).fill('140')
  await page.getByRole('button', { name: 'Move frame and members', exact: true }).click()
  await expect(page.locator('#frameHistory')).toContainText('Saving frame operation')
  await page.locator('#boardSelect').selectOption('other')
  finish()
  await expect(page.locator('#btnFrame')).toBeEnabled()
  await expect(page.locator('.canvas-frame')).toHaveCount(0)
  const other = await page.request.get(`${app.url}/api/board?board=other`)
  expect((await other.json()).layout.frames).toEqual({})
  await page.unroute('**/api/layout')
  await page.locator('#boardSelect').selectOption('default')
  await expect(page.locator('.canvas-frame')).toHaveCount(1)
  await expect(page.locator('#btnFrameUndo')).toBeEnabled()
  expect((await layout(page)).frames[id].x).toBe(140)
  await saved(page, () => page.locator('#btnFrameUndo').click())
  expect((await layout(page)).frames[id].x).toBe(40)
})

test('frame panel preserves ticket drafts and fits the narrow-screen layout', async ({ app, page }) => {
  const a = await app.create('Keep ticket draft', { x: 80, y: 100 })
  await page.goto(app.url)
  await expect(page.locator('.card')).toHaveCount(1)
  await page.locator(`.card[data-id="${a.id}"] .card-title`).click()
  const title = page.locator('#fTitle')
  // A focused input draft should not be unmounted by selecting a frame.
  await title.focus()
  const node = await title.elementHandle()
  const id = await createFrame(page, 'Delivery', 40, 60, 500, 500)
  expect(await node!.evaluate(el => el.isConnected)).toBe(true)
  await page.setViewportSize({ width: 390, height: 844 })
  await page.locator('#btnFit').click()
  const panel = await page.locator('#framePanel').boundingBox()
  const stage = await page.locator('#stage').boundingBox()
  expect(panel!.width).toBeLessThanOrEqual(390)
  expect(panel!.y).toBeGreaterThan(stage!.y)
  expect((await layout(page)).frames[id].members).toEqual([a.id])
  expect(await node!.evaluate(el => el.isConnected)).toBe(true)
})

test('failed frame saves and cancelled drafts leave persisted state unchanged; read-only blocks writes', async ({ app, page }) => {
  await app.create('Member', { x: 80, y: 100 })
  await page.goto(app.url)
  await expect(page.locator('.card')).toHaveCount(1)
  await createFrame(page, 'Delivery', 40, 60, 500, 500)
  const baseline = await layout(page)
  await page.route('**/api/layout', route => route.fulfill({ status: 500, contentType: 'application/json', body: JSON.stringify({ code: 'failed', message: 'Simulated frame save failure' }) }))
  const panel = page.locator('#framePanel')
  await panel.getByLabel('X', { exact: true }).fill('140')
  await panel.getByRole('button', { name: 'Move frame and members', exact: true }).click()
  await expect(panel.getByRole('alert')).toContainText('Simulated frame save failure')
  expect(await layout(page)).toEqual(baseline)
  await panel.getByLabel('X', { exact: true }).press('Escape')
  await expect(panel.getByLabel('X', { exact: true })).toHaveValue('40')
  expect(await layout(page)).toEqual(baseline)
  await page.unroute('**/api/layout')
  await page.goto(await app.readOnlyURL())
  await expect(page.locator('#btnFrame')).toBeDisabled()
  await page.locator('.canvas-frame-title').click()
  await expect(page.getByRole('button', { name: 'Move frame and members', exact: true })).toBeDisabled()
  await expect(page.getByRole('button', { name: 'Delete frame only', exact: true })).toBeDisabled()
})
